[package]
org = "windhoek"
name = "transport_service"
version = "1.0.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.33"

[[platform.java11.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.9.0"